use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    // Get the current date and time
    let output = Command::new("date")
        .arg("+%Y-%m-%d %H:%M:%S")
        .output()
        .expect("Failed to execute date command");

    let datetime = String::from_utf8_lossy(&output.stdout);
    let datetime = datetime.trim();

    // Split into date and time
    let parts: Vec<&str> = datetime.split_whitespace().collect();
    if parts.len() == 2 {
        println!("cargo:rustc-env=BUILD_DATE={}", parts[0]);
        println!("cargo:rustc-env=BUILD_TIME={}", parts[1]);
    } else {
        println!("cargo:rustc-env=BUILD_DATE=unknown");
        println!("cargo:rustc-env=BUILD_TIME=unknown");
    }

    // Generate demo scripts code
    generate_demo_scripts();
}

fn generate_demo_scripts() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("demo_scripts.rs");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // Scan tests/scripts directory for .sheet files
    let scripts_dir = Path::new(&manifest_dir).join("tests/scripts");
    let mut entries: Vec<_> = fs::read_dir(&scripts_dir)
        .expect("Failed to read tests/scripts directory")
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .and_then(|s| s.to_str())
                .map(|s| s == "sheet")
                .unwrap_or(false)
        })
        .collect();

    // Sort entries by filename
    entries.sort_by_key(|e| e.file_name());

    // Generate code
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs\n\n");
    code.push_str("pub fn get_demo_script(n: u8) -> Option<&'static str> {\n");
    code.push_str("    match n {\n");

    for (index, entry) in entries.iter().enumerate() {
        let filename = entry.file_name();
        let filename_str = filename.to_str().unwrap();
        let path = entry.path();
        let path_str = path.to_str().unwrap();

        code.push_str(&format!(
            "        {} => Some(include_str!(\"{}\")), // {}\n",
            index + 1,
            path_str,
            filename_str
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Generate function to get demo count
    code.push_str(&format!(
        "pub fn get_demo_count() -> u8 {{\n    {}\n}}\n",
        entries.len()
    ));

    fs::write(&dest_path, code).unwrap();

    // Tell cargo to rerun if scripts directory changes
    println!("cargo:rerun-if-changed=tests/scripts");
}
